# Generated by Django 3.0.7 on 2020-06-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='engine',
            name='power',
            field=models.FloatField(default=None),
        ),
    ]
